#!/bin/bash
#
# FOX_LOCAL_CALLBACK_SCRIPT for Zuma SoC Pixel devices (shiba/husky/akita)
#
# Called by OrangeFox_A14.sh:
#   --first-call:  $1 = FOX_RAMDISK (after theme copy, before UPX/reduce_ramdisk_size)
#   --last-call:   $1 = FOX_TMP_WORKING_DIR (before creating flashable zip)
# Called by BOARD_RECOVERY_IMAGE_PREPARE (build/make/core/Makefile):
#   --second-call: $1 = TARGET_RECOVERY_ROOT_OUT (after device overlay + all OrangeFox, before cpio)
#

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET_DIR="$1"
CALL_TYPE="$2"

if [ -z "$TARGET_DIR" ] || [ -z "$CALL_TYPE" ]; then
    echo "Usage: $0 <target_dir> <--first-call|--second-call|--last-call>"
    exit 1
fi

# =========================================================================
# Platform detection: read .build_platform.conf generated by vendorsetup.sh
# This is the single source of truth for the target SoC family.
# Environment variables (DEVICE_BUILD_FLAG) are unreliable in make/ninja
# recipe shells — they may not propagate from the lunch session.
# =========================================================================
PLATFORM=""
BUILD_CONF="$SCRIPT_DIR/.build_platform.conf"
if [ -f "$BUILD_CONF" ]; then
    . "$BUILD_CONF"
    echo "    [CONFIG] Read platform from .build_platform.conf: PLATFORM=$PLATFORM"
else
    echo "    [CONFIG] WARNING: .build_platform.conf not found, falling back to env"
    PLATFORM="${DEVICE_BUILD_FLAG:-zuma}"
fi
: "${PLATFORM:=zuma}"

# =========================================================================
# LGZ compression configuration
# =========================================================================

# Files/directories to NEVER compress (critical for boot)
LGZ_EXCLUDE_LIST=(
    "init"
    "lgz"
    "ramdisk_snapshot"
    "linker"
    "linker64"
    "ld-android.so"
    "libbase.so"
    "libcgrouprc.so"
    "libcrypto.so"
    "libcrypto_utils.so"
    "libc++.so"
    "libc.so"
    "libcutils.so"
    "libdl.so"
    "libext2_uuid.so"
    "libext4_utils.so"
    "libfec.so"
    "libfs_mgr.so"
    "libgsi.so" 
    "libhidl-gen-utils.so"
    "libjsoncpp.so"
    "liblog.so"
    "liblogwrap.so"
    "liblp.so"
    "liblzma.so"
    "libm.so"
    "libpackagelistparser.so"
    "libpcre2.so"
    "libprocessgroup_setup.so"
    "libprocessgroup.so"
    "libselinux.so"
    "libsparse.so"
    "libsquashfs_utils.so"
    "libunwindstack.so"
    "libvendorsupport.so"
    "libz.so"
)

# Directories to scan for compressible files
LGZ_SCAN_DIRS=(
    "system/bin"
    "system/lib64"
    "vendor/bin"
    # "vendor/firmware"
    "vendor/lib64"
    "sbin"
)

# Additional file patterns to compress (fonts, resources)
LGZ_EXTRA_PATTERNS=(
    "twres/fonts/*.ttf"
    "twres/fonts/*.otf"
)

# Minimum file size to bother compressing (bytes)
LGZ_MIN_SIZE=4096

# =========================================================================
# LGZ helper functions
# =========================================================================

lgz_is_excluded() {
    local filename="$1"
    local basename
    basename="$(basename "$filename")"
    for excl in "${LGZ_EXCLUDE_LIST[@]}"; do
        if [ "$basename" = "$excl" ]; then
            return 0
        fi
    done
    return 1
}

lgz_is_elf_or_so() {
    local filepath="$1"
    # Check ELF magic: 0x7f 'E' 'L' 'F'
    local magic
    magic=$(xxd -l 4 -p "$filepath" 2>/dev/null)
    if [ "$magic" = "7f454c46" ]; then
        return 0
    fi
    return 1
}

lgz_get_host_binary() {
    # Rust compressor, prebuilt (static musl x86_64). No on-the-fly
    # compilation — binaries are maintained in include/.
    local bin="$SCRIPT_DIR/include/lgz_compress_full_x64"
    if [ -x "$bin" ]; then
        echo "$bin"
        return 0
    fi
    echo "    [LGZ] ERROR: host compressor not found/executable: $bin" >&2
    return 1
}

lgz_patch_dfe_zip() {
    # --- DFE.zip: patch NEO.config FSTAB_EXTENSION to match build platform ---
    # Must run BEFORE cluster packing: the packer ingests the zip as-is.
    local zipfile="$1"
    local zip_basename
    zip_basename="$(basename "$zipfile")"
    [ "$zip_basename" = "DFENEO.zip" ] || return 0

    local tmpdir
    tmpdir=$(mktemp -d)
    if ! unzip -q -o "$zipfile" -d "$tmpdir" 2>/dev/null; then
        echo "    [LGZ-ZIP]   DFE: WARNING: bad zip, skipping NEO.config patch"
        rm -rf "$tmpdir"
        return 0
    fi
    local neo_config
    neo_config=$(find "$tmpdir" -name "NEO.config" -type f | head -1)
    if [ -n "$neo_config" ]; then
        if grep -q '^FSTAB_EXTENSION=' "$neo_config"; then
            sed -i "s/^FSTAB_EXTENSION=.*/FSTAB_EXTENSION=$PLATFORM/" "$neo_config"
            echo "    [LGZ-ZIP]   DFE: patched NEO.config FSTAB_EXTENSION=$PLATFORM"
            local new_zip="${zipfile}.dfe_new"
            ( cd "$tmpdir" && zip -0 -r -q "$new_zip" . 2>/dev/null ) \
                && mv -f "$new_zip" "$zipfile"
        else
            echo "    [LGZ-ZIP]   DFE: WARNING: FSTAB_EXTENSION not found in NEO.config"
        fi
    else
        echo "    [LGZ-ZIP]   DFE: WARNING: NEO.config not found inside DFE.zip"
    fi
    rm -rf "$tmpdir"
}

# Worker threads for the packer. nproc is BANNED in make recipe shells
# (Android PATH_Tools: non-hermetic), so fall back down the chain.
# NOTE: level 0 packs serially by design; threads matter for level 1+.
lgz_detect_jobs() {
    local jobs
    jobs=$(nproc 2>/dev/null) && [ "$jobs" -gt 0 ] 2>/dev/null && {
        echo "$jobs"
        return 0
    }
    jobs=$(getconf _NPROCESSORS_ONLN 2>/dev/null) && [ "$jobs" -gt 0 ] 2>/dev/null && {
        echo "$jobs"
        return 0
    }
    jobs=$(grep -c ^processor /proc/cpuinfo 2>/dev/null) && [ "$jobs" -gt 0 ] 2>/dev/null && {
        echo "$jobs"
        return 0
    }
    echo 4
}

# Emit one pack manifest line with EXPLICIT metadata captured right now.
# Rationale: `- - -` + --preserve-all left owner at the tool default
# (65534) in real builds, so record mode/owner deterministically via stat.
# Context stays `-`: build hosts cannot reliably read SELinux xattrs.
lgz_manifest_entry() {
    local kind="$1" filepath="$2" relpath="$3"
    local mode owner
    mode=$(stat -c%a "$filepath" 2>/dev/null || echo "644")
    owner=$(stat -c%u:%g "$filepath" 2>/dev/null || echo "0:0")
    echo "$kind $relpath $mode $owner -"
}

lgz_compress_ramdisk() {
    local ramdisk_root="$1"
    local lgz_bin
    lgz_bin=$(lgz_get_host_binary)

    if [ -z "$lgz_bin" ]; then
        echo "    [LGZ] ERROR: lgz host binary not found, skipping compression"
        return 1
    fi

    echo "    [LGZ] Using compressor: $lgz_bin"

    # Install the on-device decompressor FIRST: init needs it at
    # /system/bin/lgz for cluster unpack, and the "lgz" basename is in
    # LGZ_EXCLUDE_LIST so the pack scan skips it.
    local target_lgz_dir="$ramdisk_root/system/bin"
    mkdir -p "$target_lgz_dir"
    cp -f "$SCRIPT_DIR/include/lgz_compress_lean_arm64" "$target_lgz_dir/lgz"
    chmod 755 "$target_lgz_dir/lgz"
    echo "    [LGZ] Installed device decompressor to /system/bin/lgz"

    local level="${LGZ_LEVEL:-0}"
    local min_zip_size=102400   # zips >= 100 KB join the cluster via ingestion
    local cluster="$ramdisk_root/lgz_cluster.lgz"
    local pack_manifest packed_list
    pack_manifest=$(mktemp)
    packed_list=$(mktemp)

    echo "# LGZ cluster pack manifest (UCOMP02, generated $(date -u))" > "$pack_manifest"

    # Collect ELF binaries and shared libraries as `file` entries
    for scan_dir in "${LGZ_SCAN_DIRS[@]}"; do
        local full_dir="$ramdisk_root/$scan_dir"
        [ -d "$full_dir" ] || continue

        echo "    [LGZ] Scanning: $scan_dir"

        while IFS= read -r filepath; do
            local relpath="${filepath#$ramdisk_root/}"
            local basename
            basename="$(basename "$filepath")"

            # Skip excluded files
            if lgz_is_excluded "$filepath"; then
                echo "    [LGZ]   SKIP (excluded): $relpath"
                continue
            fi

            # Skip files that are too small
            local filesize
            filesize=$(stat -c%s "$filepath" 2>/dev/null || echo 0)
            if [ "$filesize" -lt "$LGZ_MIN_SIZE" ]; then
                continue
            fi

            # Only pack ELF binaries and .so files
            if ! lgz_is_elf_or_so "$filepath"; then
                case "$basename" in
                    *.so|*.so.*)
                        ;;
                    *)
                        continue
                        ;;
                esac
            fi

            lgz_manifest_entry file "$filepath" "$relpath" >> "$pack_manifest"
            echo "$filepath" >> "$packed_list"
        done < <(find "$full_dir" -type f | sort)
    done

    # Fonts and other resource files as `file` entries (pure LZMA2 data)
    for pattern in "${LGZ_EXTRA_PATTERNS[@]}"; do
        for filepath in $ramdisk_root/$pattern; do
            [ -f "$filepath" ] || continue

            local relpath="${filepath#$ramdisk_root/}"
            local filesize
            filesize=$(stat -c%s "$filepath" 2>/dev/null || echo 0)

            if [ "$filesize" -lt "$LGZ_MIN_SIZE" ]; then
                continue
            fi

            lgz_manifest_entry file "$filepath" "$relpath" >> "$pack_manifest"
            echo "$filepath" >> "$packed_list"
        done
    done

    # Large zips join the cluster via transparent ingestion.
    # DFE.zip gets its NEO.config patched BEFORE packing.
    while IFS= read -r zipfile; do
        local zip_size
        zip_size=$(stat -c%s "$zipfile" 2>/dev/null || echo 0)
        if [ "$zip_size" -lt "$min_zip_size" ]; then
            continue
        fi

        lgz_patch_dfe_zip "$zipfile"

        local relpath="${zipfile#$ramdisk_root/}"
        echo "    [LGZ-ZIP] Ingest: $relpath ($zip_size bytes)"
        lgz_manifest_entry zip "$zipfile" "$relpath" >> "$pack_manifest"
        echo "$zipfile" >> "$packed_list"
    done < <(find "$ramdisk_root" -name '*.zip' -type f | sort)

    local entry_count
    entry_count=$(grep -c -E '^(file|zip) ' "$pack_manifest" 2>/dev/null || echo 0)
    # grep -c prints "0" AND fails when nothing matches, so normalize.
    entry_count=$(printf '%s' "$entry_count" | tr -d -c '0-9' | tail -c 20)
    entry_count="${entry_count:-0}"
    if [ "$entry_count" -eq 0 ]; then
        echo "    [LGZ] No files to pack — continuing to snapshot generation"
        rm -f "$pack_manifest" "$packed_list" "$cluster"
        pack_ok=0
    else

    local total_original=0
    while IFS= read -r packed; do
        local sz
        sz=$(stat -c%s "$packed" 2>/dev/null || echo 0)
        total_original=$((total_original + sz))
    done < "$packed_list"

    # Pack: manifest paths are relative, so run from the ramdisk root.
    # --preserve-all stores perms/owner from the FS for correct restore.
    local lgz_jobs
    lgz_jobs=$(lgz_detect_jobs)
    echo "    [LGZ] Packing $entry_count entries (level $level, $lgz_jobs threads)..."
    ( cd "$ramdisk_root" && "$lgz_bin" pack "$pack_manifest" "$cluster" \
        -l "$level" -j "$lgz_jobs" --preserve-all )
    local pack_rc=$?

    local cluster_size
    cluster_size=$(stat -c%s "$cluster" 2>/dev/null || echo 0)

    local pack_ok=1
    if [ "$pack_rc" -ne 0 ]; then
        echo "    [LGZ] ERROR: pack tool failed (rc=$pack_rc, entries=$entry_count) — keeping originals"
        echo "    [LGZ] ERROR: command was: $lgz_bin pack <manifest:$entry_count entries> $cluster -l $level"
        pack_ok=0
    elif [ "$cluster_size" -le 0 ]; then
        echo "    [LGZ] ERROR: pack produced empty cluster — keeping originals"
        pack_ok=0
    elif [ "$cluster_size" -ge "$total_original" ]; then
        echo "    [LGZ] Pack provided no gain (orig $total_original, cluster $cluster_size) — keeping originals"
        pack_ok=0
    elif ! "$lgz_bin" list "$cluster" >/dev/null 2>&1; then
        echo "    [LGZ] ERROR: cluster failed self-check (list) — keeping originals"
        pack_ok=0
    fi

    if [ "$pack_ok" -eq 0 ]; then
        rm -f "$pack_manifest" "$packed_list" "$cluster"
    else
        # Prune originals: the cluster is the only copy now.
        # Only packed files/zips are removed; dirs and symlinks stay in place.
        while IFS= read -r orig; do
            rm -f "$orig"
        done < "$packed_list"
        rm -f "$pack_manifest" "$packed_list"

        local saved=$((total_original - cluster_size))
        local ratio=$((cluster_size * 100 / total_original))
        echo ""
        echo "    [LGZ] ========================================="
        echo "    [LGZ] Cluster pack complete!"
        echo "    [LGZ]   Entries packed:  $entry_count"
        echo "    [LGZ]   Original total:  $total_original bytes"
        echo "    [LGZ]   Cluster total:   $cluster_size bytes"
        echo "    [LGZ]   Space saved:     $saved bytes (${ratio}%)"
        echo "    [LGZ]   Cluster:         /lgz_cluster.lgz"
        echo "    [LGZ] ========================================="
    fi
    fi # entry_count > 0 (pack attempted)

    # NOTE: snapshot/file-list generation below ALWAYS runs, even when
    # packing was skipped or failed — reflash needs these lists.

    # Generate ramdisk snapshot manifest and cpio file lists using find.
    # We build our own manifest instead of relying on builder-generated
    # ramdisk-files.txt (which may not exist when this callback runs).
    local snapshot_manifest="$ramdisk_root/ramdisk_snapshot_manifest.txt"

    # Derive vendor_ramdisk path (first_stage ramdisk is a separate directory)
    # recovery/root/ -> product_out/vendor_ramdisk/
    local product_out
    product_out="$(dirname "$(dirname "$ramdisk_root")")"
    local vendor_ramdisk_dir="$product_out/vendor_ramdisk"

    echo "    [LGZ] Generating ramdisk snapshot manifest..."

    # Create file lists FIRST so they are discovered by the manifest find.
    # This ensures ramdisk_snapshot copies them to the snapshot at runtime.

    # 1. Recovery cpio file list (everything in recovery/root/)
    pushd "$ramdisk_root" > /dev/null
    find . | sed 's|^\./||; /^$/d' | sort > "$ramdisk_root/recovery_file_list.txt"
    popd > /dev/null

    # 2. First stage ramdisk cpio file list (from vendor_ramdisk/ directory)
    if [ -d "$vendor_ramdisk_dir/first_stage_ramdisk" ]; then
        pushd "$vendor_ramdisk_dir" > /dev/null
        find first_stage_ramdisk | sort > "$ramdisk_root/first_stage_file_list.txt"
        popd > /dev/null
        echo "    [LGZ] First stage ramdisk found at: $vendor_ramdisk_dir"
    else
        echo "    [LGZ] WARNING: vendor_ramdisk/first_stage_ramdisk not found"
    fi

    # 3. Comprehensive manifest with permissions for ramdisk_snapshot binary
    # Generated AFTER file lists so they are included in the manifest.
    {
        echo "# Ramdisk snapshot manifest"
        echo "# Format: <type> <octal_perms> <uid> <gid> <path>"
        echo "# For symlinks: l <perms> <uid> <gid> <path> -> <target>"
        echo "# Generated: $(date -u)"

        # Recovery ramdisk entries
        pushd "$ramdisk_root" > /dev/null
        find . \( -type l -printf 'l %m %U %G %p -> %l\n' \) \
               -o \( -type d -printf 'd %m %U %G %p\n' \) \
               -o \( -type f -printf 'f %m %U %G %p\n' \) | \
            sed 's| \.$| /|; s| \./| /|'
        popd > /dev/null

        # Vendor ramdisk (first_stage) entries
        if [ -d "$vendor_ramdisk_dir" ]; then
            pushd "$vendor_ramdisk_dir" > /dev/null
            find . -mindepth 1 \( -type l -printf 'l %m %U %G %p -> %l\n' \) \
                   -o \( -type d -printf 'd %m %U %G %p\n' \) \
                   -o \( -type f -printf 'f %m %U %G %p\n' \) | \
                sed 's| \./| /|'
            popd > /dev/null
        fi
    } | sort -t' ' -k5 > "$snapshot_manifest"

    local snap_count recovery_count fstage_count
    snap_count=$(grep -c '^[dfl]' "$snapshot_manifest" 2>/dev/null || echo 0)
    recovery_count=$(wc -l < "$ramdisk_root/recovery_file_list.txt" 2>/dev/null || echo 0)
    fstage_count=$(wc -l < "$ramdisk_root/first_stage_file_list.txt" 2>/dev/null || echo 0)
    echo "    [LGZ] Ramdisk snapshot manifest: $snap_count entries"
    echo "    [LGZ] Recovery cpio file list: $recovery_count entries"
    echo "    [LGZ] First stage cpio file list: $fstage_count entries"
}

# =========================================================================
# Main callback logic
# =========================================================================

case "$CALL_TYPE" in
    --first-call)
        echo "=== [zuma] fox_build_callback: --first-call ==="
        echo "    Ramdisk: $TARGET_DIR"
        # NOTE: UI XML pages are patched natively in the tree
        # (patches/files/.../pages/*.xml) — no overlay step needed.
        ;;

    --second-call)
        echo "=== [zuma] fox_build_callback: --second-call ==="
        echo "    Ramdisk: $TARGET_DIR (final, pre-cpio)"

        # --- Per-platform twrp.flags injection ---
        # GS201 uses UFS controller at 14700000 (vs 13200000 for zuma/zumapro).
        # The default twrp.flags uses 13200000.ufs paths; gs201 needs 14700000.ufs.
        # A twrp_gs201.flags variant is included in the ramdisk for runtime swap;
        # this build-time copy ensures the correct flags file is the default.
        platform="$PLATFORM"
        if [ "$platform" = "gs201" ]; then
            gs201_flags="$TARGET_DIR/system/etc/twrp_gs201.flags"
            default_flags="$TARGET_DIR/system/etc/twrp.flags"
            if [ -f "$gs201_flags" ]; then
                echo "    [PLATFORM] Swapping twrp.flags for gs201 (UFS 14700000)"
                cp -f "$gs201_flags" "$default_flags"
            fi
        fi

        # --- Per-platform keymint binary injection ---
        # Zuma/Zumapro use the shared prebuilt Rust keymint from
        # families/common/keymint/bin/hw/ (one binary for both).
        # GS201 uses C++ keymint built from source (system/core/trusty/keymaster)
        # via PRODUCT_PACKAGES; soong places it at $PRODUCT_OUT/vendor/bin/hw/.
        # VINTF keymint fragments live in families/<platform>/etc/.
        family_dir="$SCRIPT_DIR/families/$platform"
        common_keymint_bin="$SCRIPT_DIR/families/common/keymint/bin"
        PRODUCT_OUT="${TARGET_DIR%/recovery/root}"

        echo "    [PLATFORM] Injecting keymint for: $platform"

        # --- Keymint binary ---
        if [ "$platform" = "gs201" ]; then
            # GS201: copy source-built C++ keymint from soong vendor output
            src_bin="$PRODUCT_OUT/vendor/bin/hw/android.hardware.security.keymint-service.trusty"
            if [ -f "$src_bin" ]; then
                mkdir -p "$TARGET_DIR/vendor/bin/hw"
                cp -f "$src_bin" "$TARGET_DIR/vendor/bin/hw/"
                chmod 755 "$TARGET_DIR/vendor/bin/hw/android.hardware.security.keymint-service.trusty"
                echo "    [PLATFORM]   + C++ keymint binary (source-built)"
            else
                echo "    [PLATFORM] ERROR: C++ keymint binary not found at: $src_bin"
                echo "    [PLATFORM]   Ensure PRODUCT_PACKAGES includes keymint-service.trusty"
            fi
        else
            # Zuma/Zumapro: copy shared prebuilt Rust keymint
            if [ -d "$common_keymint_bin" ]; then
                cp -af "$common_keymint_bin" "$TARGET_DIR/vendor/"
                find "$TARGET_DIR/vendor/bin/hw" -type f -exec chmod 755 {} +
                echo "    [PLATFORM]   + Rust keymint binary (prebuilt)"
            else
                echo "    [PLATFORM] WARNING: No prebuilt keymint bin dir"
            fi
        fi

        # --- VINTF keymint fragment (per family) ---
        if [ -d "$family_dir/etc" ]; then
            cp -af "$family_dir/etc" "$TARGET_DIR/vendor/"
            echo "    [PLATFORM]   + VINTF keymint fragment"
        fi

        # --- Disable the keymint service that doesn't match this platform ---
        rc_file="$TARGET_DIR/init.recovery.pixel_common.rc"
        if [ -f "$rc_file" ]; then
            if [ "$platform" = "gs201" ]; then
                # GS201: disable Rust keymint start (no Rust binary)
                sed -i 's/^\(    start vendor\.keymint\.rust-trusty\)/#\1  # disabled for gs201/' "$rc_file"
                echo "    [PLATFORM]   + disabled Rust keymint start"
            else
                # Zuma/Zumapro: disable C++ keymint start (no C++ binary)
                sed -i 's/^\(    start vendor\.keymint-trusty\)/#\1  # disabled for '"$platform"'/' "$rc_file"
                echo "    [PLATFORM]   + disabled C++ keymint start"
            fi
        fi

        # --- LGZ: Compress ramdisk binaries for space savings ---
        echo ""
        echo "    === LGZ Ramdisk Compression ==="
        lgz_compress_ramdisk "$TARGET_DIR"
        echo ""
        ;;

    --last-call)
        echo "=== [zuma] fox_build_callback: --last-call ==="
        echo "    Working dir: $TARGET_DIR"
        # No additional actions needed for the zip phase
        ;;

    *)
        echo "Unknown call type: $CALL_TYPE"
        ;;
esac

exit 0
