#!/bin/bash
#
# FOX_LOCAL_CALLBACK_SCRIPT for Zuma SoC Pixel devices (shiba/husky/akita)
#
# Called by OrangeFox_A14.sh:
#   --first-call:  $1 = FOX_RAMDISK (after theme copy, before UPX/reduce_ramdisk_size)
#   --last-call:   $1 = FOX_TMP_WORKING_DIR (before creating flashable zip)
# Called by BOARD_RECOVERY_IMAGE_PREPARE (build/make/core/Makefile):
#   --second-call: $1 = TARGET_RECOVERY_ROOT_OUT (after device overlay + all OrangeFox, before cpio)
#

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET_DIR="$1"
CALL_TYPE="$2"

if [ -z "$TARGET_DIR" ] || [ -z "$CALL_TYPE" ]; then
    echo "Usage: $0 <target_dir> <--first-call|--second-call|--last-call>"
    exit 1
fi

# =========================================================================
# Platform detection: read .build_platform.conf generated by vendorsetup.sh
# This is the single source of truth for the target SoC family.
# Environment variables (DEVICE_BUILD_FLAG) are unreliable in make/ninja
# recipe shells — they may not propagate from the lunch session.
# =========================================================================
PLATFORM=""
BUILD_CONF="$SCRIPT_DIR/.build_platform.conf"
if [ -f "$BUILD_CONF" ]; then
    . "$BUILD_CONF"
    echo "    [CONFIG] Read platform from .build_platform.conf: PLATFORM=$PLATFORM"
else
    echo "    [CONFIG] WARNING: .build_platform.conf not found, falling back to env"
    PLATFORM="${DEVICE_BUILD_FLAG:-zuma}"
fi
: "${PLATFORM:=zuma}"

# =========================================================================
# LGZ compression configuration
# =========================================================================

# Files/directories to NEVER compress (critical for boot)
LGZ_EXCLUDE_LIST=(
    "init"
    "lgz"
    "ramdisk_snapshot"
    "linker"
    "linker64"
    "ld-android.so"
    "libbase.so"
    "libcgrouprc.so"
    "libcrypto.so"
    "libcrypto_utils.so"
    "libc++.so"
    "libc.so"
    "libcutils.so"
    "libdl.so"
    "libext2_uuid.so"
    "libext4_utils.so"
    "libfec.so"
    "libfs_mgr.so"
    "libgsi.so" 
    "libhidl-gen-utils.so"
    "libjsoncpp.so"
    "liblog.so"
    "liblogwrap.so"
    "liblp.so"
    "liblzma.so"
    "libm.so"
    "libpackagelistparser.so"
    "libpcre2.so"
    "libprocessgroup_setup.so"
    "libprocessgroup.so"
    "libselinux.so"
    "libsparse.so"
    "libsquashfs_utils.so"
    "libunwindstack.so"
    "libvendorsupport.so"
    "libz.so"
)

# Directories to scan for compressible files
LGZ_SCAN_DIRS=(
    "system/bin"
    "system/lib64"
    "vendor/bin"
    # "vendor/firmware"
    "vendor/lib64"
    "sbin"
)

# Additional file patterns to compress (fonts, resources)
LGZ_EXTRA_PATTERNS=(
    "twres/fonts/*.ttf"
    "twres/fonts/*.otf"
)

# Minimum file size to bother compressing (bytes)
LGZ_MIN_SIZE=4096

# =========================================================================
# LGZ helper functions
# =========================================================================

lgz_is_excluded() {
    local filename="$1"
    local basename
    basename="$(basename "$filename")"
    for excl in "${LGZ_EXCLUDE_LIST[@]}"; do
        if [ "$basename" = "$excl" ]; then
            return 0
        fi
    done
    return 1
}

lgz_is_elf_or_so() {
    local filepath="$1"
    # Check ELF magic: 0x7f 'E' 'L' 'F'
    local magic
    magic=$(xxd -l 4 -p "$filepath" 2>/dev/null)
    if [ "$magic" = "7f454c46" ]; then
        return 0
    fi
    return 1
}

lgz_get_host_binary() {
    # Try to find lgz host binary
    # 1. Check if built by Android build system
    # local android_host_out="${ANDROID_HOST_OUT:-out/host/linux-x86}"
    # if [ -x "$android_host_out/bin/lgz" ]; then
    #     echo "$android_host_out/bin/lgz"
    #     return 0
    # fi

    # 2. Check if pre-built locally in device tree (v3 binary first, then legacy)
    if [ -x "$SCRIPT_DIR/selfcode/lgz/lgz_host_bin" ]; then
        echo "$SCRIPT_DIR/selfcode/lgz/lgz_host_bin"
        return 0
    fi
    if [ -x "$SCRIPT_DIR/selfcode/lgz/lgz_host" ]; then
        echo "$SCRIPT_DIR/selfcode/lgz/lgz_host"
        return 0
    fi

    # 3. Try to compile on-the-fly using 7zip LZMA SDK from AOSP tree (lgzv3.c preferred)
    local LGZ_SRC="$SCRIPT_DIR/selfcode/lgz/lgzv3.c"
    local LGZ_OUT="$SCRIPT_DIR/selfcode/lgz/lgz_host_bin"
    if [ ! -f "$LGZ_SRC" ]; then
        LGZ_SRC="$SCRIPT_DIR/selfcode/lgz/lgz.c"
        LGZ_OUT="$SCRIPT_DIR/selfcode/lgz/lgz_host"
    fi
    if [ -f "$LGZ_SRC" ]; then
        local LZMA_DIR
        LZMA_DIR="$(gettop)/external/lzma/C"
        if [ -d "$LZMA_DIR" ]; then
            echo "    [LGZ] Compiling lgz host binary from $(basename $LGZ_SRC)..."
            gcc -O3 -pipe -fopenmp -flto -I"$LZMA_DIR" -D_7ZIP_ST \
                -o "$LGZ_OUT" "$LGZ_SRC" \
                "$LZMA_DIR/Alloc.c" "$LZMA_DIR/LzFind.c" "$LZMA_DIR/LzmaDec.c" \
                "$LZMA_DIR/LzmaEnc.c" "$LZMA_DIR/Lzma2Dec.c" "$LZMA_DIR/Lzma2Enc.c" \
                "$LZMA_DIR/CpuArch.c" 2>&1
            if [ $? -eq 0 ] && [ -x "$LGZ_OUT" ]; then
                echo "$LGZ_OUT"
                return 0
            fi
            echo "    [LGZ] ERROR: Failed to compile lgz."
        else
            echo "    [LGZ] ERROR: LZMA SDK not found at $LZMA_DIR"
        fi
    fi

    return 1
}

lgz_compress_zip_contents() {
    local ramdisk_root="$1"
    local lgz_bin="$2"
    local manifest="$ramdisk_root/lgz_zip_manifest.txt"
    local min_zip_size=102400   # only process zips >= 100 KB
    local min_file_size=4096    # only compress inner files >= 4 KB
    local total_saved=0
    local zip_count=0

    [ -z "$lgz_bin" ] && return 1

    echo ""
    echo "    === LGZ Zip Inner Compression ==="

    echo "# LGZ zip inner compression manifest" > "$manifest"
    echo "# Zips whose contents were LGZ-compressed at build time" >> "$manifest"
    echo "# Generated: $(date -u)" >> "$manifest"


    while IFS= read -r zipfile; do
        local zip_size
        zip_size=$(stat -c%s "$zipfile" 2>/dev/null || echo 0)
        echo "    [LGZ-ZIP] Found zip: ${zipfile#$ramdisk_root/} (${zip_size} bytes)"
        if [ "$zip_size" -lt "$min_zip_size" ]; then
            # echo "    [LGZ-ZIP]   SKIP (too small)"
            continue
        fi

        local relpath="${zipfile#$ramdisk_root/}"
        echo "    [LGZ-ZIP] Processing: $relpath ($zip_size bytes)"

        local tmpdir
        tmpdir=$(mktemp -d)

        if ! unzip -q -o "$zipfile" -d "$tmpdir" 2>/dev/null; then
            echo "    [LGZ-ZIP]   SKIP (bad zip): $relpath"
            rm -rf "$tmpdir"
            continue
        fi

        local compressed_any=0
        local inner_saved=0

        while IFS= read -r inner_file; do
            local inner_size
            inner_size=$(stat -c%s "$inner_file" 2>/dev/null || echo 0)
            [ "$inner_size" -lt "$min_file_size" ] && continue

            local tmp_comp="${inner_file}.lgz_tmp"
            if "$lgz_bin" compress "$inner_file" "$tmp_comp" > /dev/null 2>&1; then
                local comp_size
                comp_size=$(stat -c%s "$tmp_comp" 2>/dev/null || echo 0)
                if [ "$comp_size" -gt 0 ] && [ "$comp_size" -lt "$inner_size" ]; then
                    mv -f "$tmp_comp" "$inner_file"
                    compressed_any=1
                    inner_saved=$((inner_saved + inner_size - comp_size))
                else
                    rm -f "$tmp_comp"
                fi
            else
                rm -f "$tmp_comp"
            fi
        done < <(find "$tmpdir" -type f)

        # --- DFE.zip: patch NEO.config FSTAB_EXTENSION to match build platform ---
        local zip_basename
        zip_basename="$(basename "$zipfile")"
        if [ "$zip_basename" = "DFENEO.zip" ]; then
            local neo_config
            neo_config=$(find "$tmpdir" -name "NEO.config" -type f | head -1)
            if [ -n "$neo_config" ]; then
                local platform="$PLATFORM"
                if grep -q '^FSTAB_EXTENSION=' "$neo_config"; then
                    sed -i "s/^FSTAB_EXTENSION=.*/FSTAB_EXTENSION=$platform/" "$neo_config"
                    echo "    [LGZ-ZIP]   DFE: patched NEO.config FSTAB_EXTENSION=$platform"
                    compressed_any=1
                else
                    echo "    [LGZ-ZIP]   DFE: WARNING: FSTAB_EXTENSION not found in NEO.config"
                fi
            else
                echo "    [LGZ-ZIP]   DFE: WARNING: NEO.config not found inside DFE.zip"
            fi
        fi

        if [ "$compressed_any" -eq 1 ]; then
            # Repack as store-mode zip (LZMA2 data doesn't benefit from deflate)
            local new_zip="${zipfile}.lgz_new"
            pushd "$tmpdir" > /dev/null
            zip -0 -r -q "$new_zip" . 2>/dev/null
            popd > /dev/null

            local new_size
            new_size=$(stat -c%s "$new_zip" 2>/dev/null || echo 0)

            if [ "$new_size" -gt 0 ] && [ "$new_size" -lt "$zip_size" ]; then
                local ratio=$((new_size * 100 / zip_size))
                echo "    [LGZ-ZIP]   OK: $relpath ($zip_size -> $new_size, ${ratio}%)"
                
                # Тупо и жестко: удаляем оригинал и копируем сжатый
                rm -f "$zipfile"
                cp -f "$new_zip" "$zipfile"
                
                # Проверяем, применился ли размер на диск
                local verify_size=$(stat -c%s "$zipfile" 2>/dev/null || echo 0)
                if [ "$verify_size" != "$new_size" ]; then
                    echo "    [LGZ-ZIP]   WTF ERROR: File did not overwrite! Expected $new_size, got $verify_size"
                fi
                
                echo "/$relpath" >> "$manifest"
                total_saved=$((total_saved + zip_size - new_size))
                zip_count=$((zip_count + 1))
                rm -f "$new_zip"
            else
                echo "    [LGZ-ZIP]   SKIP (no gain): $relpath"
                rm -f "$new_zip"
            fi
        else
            echo "    [LGZ-ZIP]   SKIP (nothing compressible): $relpath"
        fi

        rm -rf "$tmpdir"
    done < <(find "$ramdisk_root" -name '*.zip' -type f | sort)

    if [ "$zip_count" -gt 0 ]; then
        echo "    [LGZ-ZIP] ========================================="
        echo "    [LGZ-ZIP] Zip inner compression complete!"
        echo "    [LGZ-ZIP]   Archives processed: $zip_count"
        echo "    [LGZ-ZIP]   Total saved: $total_saved bytes"
        echo "    [LGZ-ZIP] ========================================="
    else
        echo "    [LGZ-ZIP] No zip archives benefited from inner compression"
        rm -f "$manifest"
    fi
}

lgz_compress_ramdisk() {
    local ramdisk_root="$1"
    local lgz_bin
    lgz_bin=$(lgz_get_host_binary)

    if [ -z "$lgz_bin" ]; then
        echo "    [LGZ] ERROR: lgz host binary not found, skipping compression"
        return 1
    fi

    echo "    [LGZ] Using compressor: $lgz_bin"

    local manifest_file="$ramdisk_root/lgz_compressed_files.txt"
    local total_original=0
    local total_compressed=0
    local file_count=0

    # Clear manifest
    echo "# LGZ compressed files manifest" > "$manifest_file"
    echo "# Format: <octal_permissions> <path_in_ramdisk>" >> "$manifest_file"
    echo "# Generated: $(date -u)" >> "$manifest_file"

    # Scan ELF binaries and shared libraries
    for scan_dir in "${LGZ_SCAN_DIRS[@]}"; do
        local full_dir="$ramdisk_root/$scan_dir"
        [ -d "$full_dir" ] || continue

        echo "    [LGZ] Scanning: $scan_dir"

        while IFS= read -r filepath; do
            local relpath="${filepath#$ramdisk_root/}"
            local basename
            basename="$(basename "$filepath")"

            # Skip excluded files
            if lgz_is_excluded "$filepath"; then
                echo "    [LGZ]   SKIP (excluded): $relpath"
                continue
            fi

            # Skip files that are too small
            local filesize
            filesize=$(stat -c%s "$filepath" 2>/dev/null || echo 0)
            if [ "$filesize" -lt "$LGZ_MIN_SIZE" ]; then
                continue
            fi

            # Only compress ELF binaries and .so files
            if ! lgz_is_elf_or_so "$filepath"; then
                # Check if it's a .so by extension (some stripped .so may fail magic check)
                case "$basename" in
                    *.so|*.so.*)
                        ;;
                    *)
                        # Если файл находится в директории firmware, сжимаем его (игнорируем фильтр)
                        if [[ "$relpath" == *vendor/firmware/* ]]; then
                            # Ничего не делаем, идем дальше к сжатию
                            : 
                        else
                            continue
                        fi
                        ;;
                esac
            fi

            # Save original permissions
            local orig_perms
            orig_perms=$(stat -c%a "$filepath" 2>/dev/null || echo "755")

            # Compress
            local tmp_compressed="${filepath}.lgz_tmp"
            if "$lgz_bin" compress "$filepath" "$tmp_compressed" > /dev/null 2>&1; then
                local comp_size
                comp_size=$(stat -c%s "$tmp_compressed" 2>/dev/null || echo 0)

                # Only replace if compressed is smaller
                if [ "$comp_size" -gt 0 ] && [ "$comp_size" -lt "$filesize" ]; then
                    local ratio=$((comp_size * 100 / filesize))
                    echo "    [LGZ]   OK: $relpath ($filesize -> $comp_size bytes, ${ratio}%)"

                    mv -f "$tmp_compressed" "$filepath"
                    chmod "$orig_perms" "$filepath"

                    echo "$orig_perms /$relpath" >> "$manifest_file"
                    total_original=$((total_original + filesize))
                    total_compressed=$((total_compressed + comp_size))
                    file_count=$((file_count + 1))
                else
                    echo "    [LGZ]   SKIP (no gain): $relpath"
                    rm -f "$tmp_compressed"
                fi
            else
                echo "    [LGZ]   FAIL: $relpath"
                rm -f "$tmp_compressed"
            fi
        done < <(find "$full_dir" -type f | sort)
    done

    # Compress fonts and other resource files (non-ELF, pure LZMA2)
    for pattern in "${LGZ_EXTRA_PATTERNS[@]}"; do
        for filepath in $ramdisk_root/$pattern; do
            [ -f "$filepath" ] || continue

            local relpath="${filepath#$ramdisk_root/}"
            local filesize
            filesize=$(stat -c%s "$filepath" 2>/dev/null || echo 0)

            if [ "$filesize" -lt "$LGZ_MIN_SIZE" ]; then
                continue
            fi

            local orig_perms
            orig_perms=$(stat -c%a "$filepath" 2>/dev/null || echo "644")

            local tmp_compressed="${filepath}.lgz_tmp"
            if "$lgz_bin" compress "$filepath" "$tmp_compressed" > /dev/null 2>&1; then
                local comp_size
                comp_size=$(stat -c%s "$tmp_compressed" 2>/dev/null || echo 0)

                if [ "$comp_size" -gt 0 ] && [ "$comp_size" -lt "$filesize" ]; then
                    local ratio=$((comp_size * 100 / filesize))
                    echo "    [LGZ]   OK: $relpath ($filesize -> $comp_size bytes, ${ratio}%)"

                    mv -f "$tmp_compressed" "$filepath"
                    chmod "$orig_perms" "$filepath"

                    echo "$orig_perms /$relpath" >> "$manifest_file"
                    total_original=$((total_original + filesize))
                    total_compressed=$((total_compressed + comp_size))
                    file_count=$((file_count + 1))
                else
                    echo "    [LGZ]   SKIP (no gain): $relpath"
                    rm -f "$tmp_compressed"
                fi
            else
                rm -f "$tmp_compressed"
            fi
        done
    done

    # Copy lgz binary into ramdisk for runtime decompression
    local lgz_device_bin="$SCRIPT_DIR/selfcode/lgz/lgz_device"
    local target_lgz_dir="$ramdisk_root/system/bin"
    mkdir -p "$target_lgz_dir"

    # If we have a pre-built device binary, use it; otherwise it's built by Android.bp
    if [ -f "$lgz_device_bin" ]; then
        echo "    [LGZ] Installing lgz device binary to /system/bin/lgz"
        cp -f "$lgz_device_bin" "$target_lgz_dir/lgz"
        chmod 755 "$target_lgz_dir/lgz"
    fi

    # Compress files INSIDE zip archives (LZMA2 beats deflate on binaries)
    lgz_compress_zip_contents "$ramdisk_root" "$lgz_bin"

    # Generate ramdisk snapshot manifest and cpio file lists using find.
    # We build our own manifest instead of relying on builder-generated
    # ramdisk-files.txt (which may not exist when this callback runs).
    local snapshot_manifest="$ramdisk_root/ramdisk_snapshot_manifest.txt"

    # Derive vendor_ramdisk path (first_stage ramdisk is a separate directory)
    # recovery/root/ -> product_out/vendor_ramdisk/
    local product_out
    product_out="$(dirname "$(dirname "$ramdisk_root")")"
    local vendor_ramdisk_dir="$product_out/vendor_ramdisk"

    echo "    [LGZ] Generating ramdisk snapshot manifest..."

    # Create file lists FIRST so they are discovered by the manifest find.
    # This ensures ramdisk_snapshot copies them to the snapshot at runtime.

    # 1. Recovery cpio file list (everything in recovery/root/)
    pushd "$ramdisk_root" > /dev/null
    find . | sed 's|^\./||; /^$/d' | sort > "$ramdisk_root/recovery_file_list.txt"
    popd > /dev/null

    # 2. First stage ramdisk cpio file list (from vendor_ramdisk/ directory)
    if [ -d "$vendor_ramdisk_dir/first_stage_ramdisk" ]; then
        pushd "$vendor_ramdisk_dir" > /dev/null
        find first_stage_ramdisk | sort > "$ramdisk_root/first_stage_file_list.txt"
        popd > /dev/null
        echo "    [LGZ] First stage ramdisk found at: $vendor_ramdisk_dir"
    else
        echo "    [LGZ] WARNING: vendor_ramdisk/first_stage_ramdisk not found"
    fi

    # 3. Comprehensive manifest with permissions for ramdisk_snapshot binary
    # Generated AFTER file lists so they are included in the manifest.
    {
        echo "# Ramdisk snapshot manifest"
        echo "# Format: <type> <octal_perms> <uid> <gid> <path>"
        echo "# For symlinks: l <perms> <uid> <gid> <path> -> <target>"
        echo "# Generated: $(date -u)"

        # Recovery ramdisk entries
        pushd "$ramdisk_root" > /dev/null
        find . \( -type l -printf 'l %m %U %G %p -> %l\n' \) \
               -o \( -type d -printf 'd %m %U %G %p\n' \) \
               -o \( -type f -printf 'f %m %U %G %p\n' \) | \
            sed 's| \.$| /|; s| \./| /|'
        popd > /dev/null

        # Vendor ramdisk (first_stage) entries
        if [ -d "$vendor_ramdisk_dir" ]; then
            pushd "$vendor_ramdisk_dir" > /dev/null
            find . -mindepth 1 \( -type l -printf 'l %m %U %G %p -> %l\n' \) \
                   -o \( -type d -printf 'd %m %U %G %p\n' \) \
                   -o \( -type f -printf 'f %m %U %G %p\n' \) | \
                sed 's| \./| /|'
            popd > /dev/null
        fi
    } | sort -t' ' -k5 > "$snapshot_manifest"

    local snap_count recovery_count fstage_count
    snap_count=$(grep -c '^[dfl]' "$snapshot_manifest" 2>/dev/null || echo 0)
    recovery_count=$(wc -l < "$ramdisk_root/recovery_file_list.txt" 2>/dev/null || echo 0)
    fstage_count=$(wc -l < "$ramdisk_root/first_stage_file_list.txt" 2>/dev/null || echo 0)
    echo "    [LGZ] Ramdisk snapshot manifest: $snap_count entries"
    echo "    [LGZ] Recovery cpio file list: $recovery_count entries"
    echo "    [LGZ] First stage cpio file list: $fstage_count entries"

    # Summary
    if [ "$file_count" -gt 0 ]; then
        local saved=$((total_original - total_compressed))
        local overall_ratio=$((total_compressed * 100 / total_original))
        echo ""
        echo "    [LGZ] ========================================="
        echo "    [LGZ] Compression complete!"
        echo "    [LGZ]   Files compressed: $file_count"
        echo "    [LGZ]   Original total:   $total_original bytes"
        echo "    [LGZ]   Compressed total:  $total_compressed bytes"
        echo "    [LGZ]   Space saved:       $saved bytes (${overall_ratio}%)"
        echo "    [LGZ]   Manifest:          /lgz_compressed_files.txt"
        echo "    [LGZ] ========================================="
    else
        echo "    [LGZ] No files were compressed"
        rm -f "$manifest_file"
    fi
}

# =========================================================================
# Main callback logic
# =========================================================================

case "$CALL_TYPE" in
    --first-call)
        echo "=== [zuma] fox_build_callback: --first-call ==="
        echo "    Ramdisk: $TARGET_DIR"

        # Overlay custom UI pages over the default OrangeFox pages
        PAGES_DIR="$TARGET_DIR/twres/pages"
        if [ -d "$PAGES_DIR" ]; then
            for xml in "$SCRIPT_DIR/fox_mod_ui/"*.xml; do
                [ -f "$xml" ] || continue
                BASENAME="$(basename "$xml")"
                echo "    Replacing: twres/pages/$BASENAME"
                cp -f "$xml" "$PAGES_DIR/$BASENAME"
            done
        else
            echo "    WARNING: $PAGES_DIR not found, skipping XML overlay"
        fi


        ;;

    --second-call)
        echo "=== [zuma] fox_build_callback: --second-call ==="
        echo "    Ramdisk: $TARGET_DIR (final, pre-cpio)"

        # --- Per-platform twrp.flags injection ---
        # GS201 uses UFS controller at 14700000 (vs 13200000 for zuma/zumapro).
        # The default twrp.flags uses 13200000.ufs paths; gs201 needs 14700000.ufs.
        # A twrp_gs201.flags variant is included in the ramdisk for runtime swap;
        # this build-time copy ensures the correct flags file is the default.
        platform="$PLATFORM"
        if [ "$platform" = "gs201" ]; then
            gs201_flags="$TARGET_DIR/system/etc/twrp_gs201.flags"
            default_flags="$TARGET_DIR/system/etc/twrp.flags"
            if [ -f "$gs201_flags" ]; then
                echo "    [PLATFORM] Swapping twrp.flags for gs201 (UFS 14700000)"
                cp -f "$gs201_flags" "$default_flags"
            fi
        fi

        # --- Per-platform keymint binary injection ---
        # Zuma/Zumapro use prebuilt Rust keymint from prebuilt/<platform>/bin/hw/.
        # GS201 uses C++ keymint built from source (system/core/trusty/keymaster)
        # via PRODUCT_PACKAGES; soong places it at $PRODUCT_OUT/vendor/bin/hw/.
        # VINTF keymint fragments are always prebuilt in prebuilt/<platform>/etc/.
        prebuilt_dir="$SCRIPT_DIR/prebuilt/$platform"
        PRODUCT_OUT="${TARGET_DIR%/recovery/root}"

        echo "    [PLATFORM] Injecting keymint for: $platform"

        # --- Keymint binary ---
        if [ "$platform" = "gs201" ]; then
            # GS201: copy source-built C++ keymint from soong vendor output
            src_bin="$PRODUCT_OUT/vendor/bin/hw/android.hardware.security.keymint-service.trusty"
            if [ -f "$src_bin" ]; then
                mkdir -p "$TARGET_DIR/vendor/bin/hw"
                cp -f "$src_bin" "$TARGET_DIR/vendor/bin/hw/"
                chmod 755 "$TARGET_DIR/vendor/bin/hw/android.hardware.security.keymint-service.trusty"
                echo "    [PLATFORM]   + C++ keymint binary (source-built)"
            else
                echo "    [PLATFORM] ERROR: C++ keymint binary not found at: $src_bin"
                echo "    [PLATFORM]   Ensure PRODUCT_PACKAGES includes keymint-service.trusty"
            fi
        else
            # Zuma/Zumapro: copy prebuilt Rust keymint
            if [ -d "$prebuilt_dir/bin" ]; then
                cp -af "$prebuilt_dir/bin" "$TARGET_DIR/vendor/"
                find "$TARGET_DIR/vendor/bin/hw" -type f -exec chmod 755 {} +
                echo "    [PLATFORM]   + Rust keymint binary (prebuilt)"
            else
                echo "    [PLATFORM] WARNING: No prebuilt bin dir for $platform"
            fi
        fi

        # --- VINTF keymint fragment (always from prebuilt) ---
        if [ -d "$prebuilt_dir/etc" ]; then
            cp -af "$prebuilt_dir/etc" "$TARGET_DIR/vendor/"
            echo "    [PLATFORM]   + VINTF keymint fragment"
        fi

        # --- Disable the keymint service that doesn't match this platform ---
        rc_file="$TARGET_DIR/init.recovery.pixel_common.rc"
        if [ -f "$rc_file" ]; then
            if [ "$platform" = "gs201" ]; then
                # GS201: disable Rust keymint start (no Rust binary)
                sed -i 's/^\(    start vendor\.keymint\.rust-trusty\)/#\1  # disabled for gs201/' "$rc_file"
                echo "    [PLATFORM]   + disabled Rust keymint start"
            else
                # Zuma/Zumapro: disable C++ keymint start (no C++ binary)
                sed -i 's/^\(    start vendor\.keymint-trusty\)/#\1  # disabled for '"$platform"'/' "$rc_file"
                echo "    [PLATFORM]   + disabled C++ keymint start"
            fi
        fi

        # --- LGZ: Compress ramdisk binaries for space savings ---
        echo ""
        echo "    === LGZ Ramdisk Compression ==="
        lgz_compress_ramdisk "$TARGET_DIR"
        echo ""
        ;;

    --last-call)
        echo "=== [zuma] fox_build_callback: --last-call ==="
        echo "    Working dir: $TARGET_DIR"
        # No additional actions needed for the zip phase
        ;;

    *)
        echo "Unknown call type: $CALL_TYPE"
        ;;
esac

exit 0
