#!/bin/bash
#
# FOX_LOCAL_CALLBACK_SCRIPT for Zuma SoC Pixel devices (shiba/husky/akita)
#
# Called by OrangeFox_A14.sh:
#   --first-call:  $1 = FOX_RAMDISK (after theme copy, before UPX/reduce_ramdisk_size)
#   --last-call:   $1 = FOX_TMP_WORKING_DIR (before creating flashable zip)
# Called by BOARD_RECOVERY_IMAGE_PREPARE (build/make/core/Makefile):
#   --second-call: $1 = TARGET_RECOVERY_ROOT_OUT (after device overlay + all OrangeFox, before cpio)
#

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET_DIR="$1"
CALL_TYPE="$2"

if [ -z "$TARGET_DIR" ] || [ -z "$CALL_TYPE" ]; then
    echo "Usage: $0 <target_dir> <--first-call|--second-call|--last-call>"
    exit 1
fi

# =========================================================================
# Platform detection: read .build_platform.conf generated by vendorsetup.sh
# This is the single source of truth for the target SoC family.
# Environment variables (DEVICE_BUILD_FLAG) are unreliable in make/ninja
# recipe shells — they may not propagate from the lunch session.
# =========================================================================
PLATFORM=""
BUILD_CONF="$SCRIPT_DIR/.build_platform.conf"
if [ -f "$BUILD_CONF" ]; then
    . "$BUILD_CONF"
    echo "    [CONFIG] Read platform from .build_platform.conf: PLATFORM=$PLATFORM"
else
    echo "    [CONFIG] WARNING: .build_platform.conf not found, falling back to env"
    PLATFORM="${DEVICE_BUILD_FLAG:-zuma}"
fi
: "${PLATFORM:=zuma}"
# LGZ level arrives via .build_platform.conf (recipe shells strip custom
# env vars); fall back to env, then default 0. Validated 0-3.
: "${LGZ_LEVEL:=0}"
case "$LGZ_LEVEL" in
    0|1|2|3) ;;
    *) echo "    [CONFIG] WARNING: bad LGZ_LEVEL='$LGZ_LEVEL', using 0"; LGZ_LEVEL=0 ;;
esac
echo "    [CONFIG] LGZ_LEVEL=$LGZ_LEVEL"
# TEST toggle (see vendorsetup.sh): zuma C++ keymint from source.
# Arrives via .build_platform.conf like LGZ_LEVEL. Validated 0/1.
: "${ZUMA_CPP_KEYMINT:=0}"
case "$ZUMA_CPP_KEYMINT" in
    0|1) ;;
    *) echo "    [CONFIG] WARNING: bad ZUMA_CPP_KEYMINT='$ZUMA_CPP_KEYMINT', using 0"; ZUMA_CPP_KEYMINT=0 ;;
esac
[ "$ZUMA_CPP_KEYMINT" = "1" ] && echo "    [CONFIG] TEST: zuma C++ keymint from source (no Rust prebuilt)"

# =========================================================================
# LGZ compression configuration
# =========================================================================
# Policy (LGZ_POLICY):
#   dirs (default, production) — pack ONLY LGZ_PACK_DIRS (V9-verified set:
#     sbin x4 + system/bin x64 + system/lib64 x158 + twres/fonts x12 +
#     vendor/bin/hw x1 = 239 entries, 0 .ko / 0 .zip); everything else stays
#     open. Excludes always win.
#   all — pack EVERYTHING except LGZ_EXCLUDE_LIST into one solid cluster
#     (legacy experimental layout, max space saving).
# LGZ_EXCLUDE_LIST (init closure + unpack/snapshot tooling + libstd +
# generated lists) ALWAYS wins, in every policy.
# first_stage ramdisk (vendor_ramdisk/) is NEVER touched: it is only read
# here for file lists. Android + bootloader need it intact.
# Files/directories to NEVER compress (critical for boot)
# Boot-critical set (must be open BEFORE the cluster unpack runs):
#   init closure (linker/libs) — init itself executes pre-unpack;
#   lgz / ramdisk_snapshot + libstd.dylib.so — the unpack/snapshot tools
#     and the snapshot binary's Rust std dependency;
#   cluster + generated manifests — created by this callback post-pack.
# TEST-ONLY extras (boot-path probing, keep for now):
#   "*.rc" — all rc service definitions stay open (init.recovery.*.rc at
#     root + system/etc/init/*.rc + ueventd.rc);
#   "recovery" — /system/bin/recovery stays open so stock IsRecoveryMode
#     (access check, first-stage) and service exec never depend on unpack.
LGZ_EXCLUDE_LIST=(
    "init"
    "lgz"
    "fox_fbe_kdf"
    # "ramdisk_snapshot"
    # "recovery-pixel-boot"
    # "libstd.dylib.so"
    "*.rc"
    "recovery"
    # "linker"
    # "linker64"
    # "ld-android.so"
    # "libbase.so"
    # "libcgrouprc.so"
    # "libcrypto.so"
    # "libcrypto_utils.so"
    # "libc++.so"
    # "libc.so"
    # "libcutils.so"
    # "libdl.so"
    # "libext2_uuid.so"
    # "libext4_utils.so"
    # "libfec.so"
    # "libfs_mgr.so"
    # "libgsi.so" 
    # "libhidl-gen-utils.so"
    # "libjsoncpp.so"
    # "liblog.so"
    # "liblogwrap.so"
    # "liblp.so"
    # "liblzma.so"
    # "libm.so"
    # "libpackagelistparser.so"
    # "libpcre2.so"
    # "libprocessgroup_setup.so"
    # "libprocessgroup.so"
    # "libselinux.so"
    # "libsparse.so"
    # "libsquashfs_utils.so"
    # "libunwindstack.so"
    # "libvendorsupport.so"
    # "libz.so"
    "lgz_cluster.lgz"
    "pixelrunatboot.json"
    "ramdisk_snapshot_manifest.txt"
    "recovery_file_list.txt"
    "first_stage_file_list.txt"
    "nboot.lz4"
)

# Pack policy: dirs (default, V9-verified set) or all (legacy experimental).
# Arrives via .build_platform.conf like LGZ_LEVEL (recipe
# shells strip custom env); constant fallback keeps local/manual runs on
# the production layout.
: "${LGZ_POLICY:=dirs}"

# =========================================================================
# LGZ_PACK_DIRS — manual directory inclusions for LGZ_POLICY=dirs.
# Ramdisk-relative dirs (no leading slash). EVERYTHING underneath joins
# the cluster EXCEPT LGZ_EXCLUDE_LIST (excludes always win):
#   "twres/"                  -> all of twres/ joins...
#   "*.png" in excludes       -> ...except *.png anywhere
#   "twres/dir/file.ext"      -> except that one exact file
#   "twres/subdir/"           -> except that whole subtree
# *.zip underneath joins via transparent ingestion (restored by
# `lgz decompress` in init.cpp, like the rest of the cluster).
# Prefill = V9-verified packed set (239 entries, bootable):
# sbin x4 (aapt/ksud/magiskboot/zip) + system/bin x64 + system/lib64 x158
# + twres/fonts x12 + vendor/bin/hw x1 (keymint-service.rust.trusty).
# V9 shipped zips and .ko OPEN (0 in cluster).
# =========================================================================
LGZ_PACK_DIRS=(
    "sbin"
    "system/bin"
    "system/lib64"
    # "twres/fonts"
    "vendor/bin/hw"
    "system/etc/terminfo"
    "system/etc/nano"
    "FFiles"
    "twres"
    # --- experiment examples (uncomment to test) ---
    # "system/lib64/modules"   # hierarchical otg/susfs .ko -> cluster
    # "twres/"                 # whole twres (needs *.png excludes to test)
    # "vendor/"                # whole vendor subtree
)

# =========================================================================
# Pixel device config merge (families/*/family.json + devices/*/pixel.json
# -> /pixelrunatboot.json in the ramdisk root, always open).
# The Rust engine reads its section by ro.hardware at runtime; per-device
# vendor data (touch lists, partitions, haptics path, props) never lives
# in code. Family props merge under device props (device wins).
# Loud fail on invalid JSON — a half-merged config must never ship.
# =========================================================================
merge_pixel_config() {
    local ramdisk_root="$1" platform="$2"
    python3 - "$SCRIPT_DIR" "$ramdisk_root/pixelrunatboot.json" "$platform" <<'PYEOF'
import json, sys, pathlib
tree, out, platform = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]), sys.argv[3]
# Kernel cmdline/bootconfig normalization is shared verbatim with
# gen_kernel_mk.py (single source of truth: families/*/family.json
# `kernels` + devices/*/pixel.json overrides). The flat strings emitted
# here feed reflash_twrp.sh, which stamps them into the repacked
# vendor_boot header via `magiskboot unpack -h` substitution.
sys.path.insert(0, str(tree))
from gen_kernel_mk import norm_cmdline, effective_profile
merged = {}
families = {}
for famfile in sorted((tree / 'families').glob('*/family.json')):
    try:
        fam = json.loads(famfile.read_text())
    except Exception as e:
        print(f'    [PIXELCFG] ERROR: bad family JSON {famfile}: {e}')
        sys.exit(1)
    families[fam['family']] = fam
    merged.setdefault('_families', {})[fam['family']] = fam
n = 0
bootcfg = {}
for pixfile in sorted((tree / 'devices').glob('*/pixel.json')):
    dev = pixfile.parent.name
    if dev in merged:
        print(f'    [PIXELCFG] ERROR: duplicate device key: {dev}')
        sys.exit(1)
    try:
        pj = json.loads(pixfile.read_text())
    except Exception as e:
        print(f'    [PIXELCFG] ERROR: bad device JSON {pixfile}: {e}')
        sys.exit(1)
    # Family-scoped image: only this platform's devices ship.
    if pj.get('family') != platform:
        continue
    famprops = merged.get('_families', {}).get(pj['family'], {}).get('props', {})
    props = dict(famprops)
    props.update(pj.get('props', {}))
    pj['props'] = props
    merged[dev] = pj
    # Flat per-device kernel boot strings (author order, like VENDOR_CMDLINE).
    fam = families.get(pj['family'], {})
    # Single record: the kernel THIS image is built with. Version comes
    # from families/<fam>/.gen_kernel.mk (FOX_KERNEL_VER, written by
    # build.sh pre-lunch); env vars don't survive recipe shells.
    # No runtime detection: reflash stamps exactly this, or falls back
    # to the nboot.lz4 base header when the record is absent.
    ver = ''
    genmk = tree / 'families' / pj.get('family', '') / '.gen_kernel.mk'
    try:
        for line in genmk.read_text().splitlines():
            if line.startswith('FOX_KERNEL_VER :='):
                ver = line.split(':=', 1)[1].strip()
                break
    except OSError:
        pass
    if not ver:
        ver = fam.get('default_kernel', '')
        print(f"    [PIXELCFG] WARNING: no .gen_kernel.mk for {pj['family']}, using default_kernel={ver}")
    prof, src = effective_profile(fam, pj, ver)
    if prof is None:
        print(f'    [PIXELCFG] ERROR: no kernels[{ver}] for {dev}')
        sys.exit(1)
    flags = norm_cmdline(prof.get('cmdline', {'type': 'arr', 'value': []}))
    boot = list(prof.get('bootconfig_append', []) or [])
    bootcfg[dev] = {'ver': ver, 'cmdline': ' '.join(flags),
                    'bootconfig': '\n'.join(boot), 'source': src}
    n += 1
merged['kernel_bootcfg'] = bootcfg
out.write_text(json.dumps(merged, indent=2, ensure_ascii=False) + '\n')
print(f'    [PIXELCFG] merged {n} devices (family {platform}) -> /pixelrunatboot.json')
print(f'    [PIXELCFG] kernel_bootcfg for {len(bootcfg)} devices')
PYEOF
}

# LGZ helper functions
# =========================================================================

lgz_is_excluded() {
    local filename="$1" relpath="${2:-}"
    local basename
    basename="$(basename "$filename")"
    [ -z "$relpath" ] && relpath="$basename"
    local excl
    for excl in "${LGZ_EXCLUDE_LIST[@]}"; do
        case "$excl" in
            # Ramdisk-relative dir prefix (trailing slash): "twres/subdir/"
            # matches everything underneath it.
            */)
                local prefix="${excl%/}/"
                if [[ "$relpath" == "$prefix"* ]]; then
                    return 0
                fi
                ;;
            # Ramdisk-relative exact file: "twres/dir/file.ext".
            */*)
                if [ "$relpath" = "$excl" ]; then
                    return 0
                fi
                ;;
            # Suffix globs for test/probe layouts (e.g. "*.rc"): match by ending.
            "*."*)
                local suffix="${excl#\*}"
                if [[ "$basename" == *"$suffix" ]]; then
                    return 0
                fi
                ;;
            *)
                if [ "$basename" = "$excl" ]; then
                    return 0
                fi
                ;;
        esac
    done
    return 1
}

lgz_get_host_binary() {
    # Rust compressor, prebuilt (static musl x86_64). No on-the-fly
    # compilation — binaries are maintained in include/.
    local bin="$SCRIPT_DIR/include/lgz_compress_full_x64"
    if [ -x "$bin" ]; then
        echo "$bin"
        return 0
    fi
    echo "    [LGZ] ERROR: host compressor not found/executable: $bin" >&2
    return 1
}

lgz_patch_dfe_zip() {
    # --- DFE.zip: patch NEO.config FSTAB_EXTENSION to match build platform ---
    # Must run BEFORE cluster packing: the packer ingests the zip as-is.
    local zipfile="$1"
    local zip_basename
    zip_basename="$(basename "$zipfile")"
    [ "$zip_basename" = "DFENEO.zip" ] || return 0

    local tmpdir
    tmpdir=$(mktemp -d)
    if ! unzip -q -o "$zipfile" -d "$tmpdir" 2>/dev/null; then
        echo "    [LGZ-ZIP]   DFE: WARNING: bad zip, skipping NEO.config patch"
        rm -rf "$tmpdir"
        return 0
    fi
    local neo_config
    neo_config=$(find "$tmpdir" -name "NEO.config" -type f | head -1)
    if [ -n "$neo_config" ]; then
        if grep -q '^FSTAB_EXTENSION=' "$neo_config"; then
            sed -i "s/^FSTAB_EXTENSION=.*/FSTAB_EXTENSION=$PLATFORM/" "$neo_config"
            echo "    [LGZ-ZIP]   DFE: patched NEO.config FSTAB_EXTENSION=$PLATFORM"
            local new_zip="${zipfile}.dfe_new"
            ( cd "$tmpdir" && zip -0 -r -q "$new_zip" . 2>/dev/null ) \
                && mv -f "$new_zip" "$zipfile"
        else
            echo "    [LGZ-ZIP]   DFE: WARNING: FSTAB_EXTENSION not found in NEO.config"
        fi
    else
        echo "    [LGZ-ZIP]   DFE: WARNING: NEO.config not found inside DFE.zip"
    fi
    rm -rf "$tmpdir"
}

# Worker threads for the packer. nproc is BANNED in make recipe shells
# (Android PATH_Tools: non-hermetic), so fall back down the chain.
# NOTE: level 0 packs serially by design; threads matter for level 1+.
lgz_detect_jobs() {
    local jobs
    jobs=$(nproc 2>/dev/null) && [ "$jobs" -gt 0 ] 2>/dev/null && {
        echo "$jobs"
        return 0
    }
    jobs=$(getconf _NPROCESSORS_ONLN 2>/dev/null) && [ "$jobs" -gt 0 ] 2>/dev/null && {
        echo "$jobs"
        return 0
    }
    jobs=$(grep -c ^processor /proc/cpuinfo 2>/dev/null) && [ "$jobs" -gt 0 ] 2>/dev/null && {
        echo "$jobs"
        return 0
    }
    echo 4
}

# Emit one pack manifest line with EXPLICIT metadata.
# Mode comes from stat; owner is forced to root (ramdisk norm — image
# assembly normalizes to root anyway, and staging owners are unreliable:
# sandboxed build shells may stage files as 65534). Context stays `-`:
# build hosts cannot reliably read SELinux xattrs.
lgz_manifest_entry() {
    local kind="$1" filepath="$2" relpath="$3"
    local mode
    mode=$(stat -c%a "$filepath" 2>/dev/null || echo "644")
    echo "$kind $relpath $mode 0:0 -"
}

lgz_compress_ramdisk() {
    local ramdisk_root="$1"
    local lgz_bin
    lgz_bin=$(lgz_get_host_binary)

    if [ -z "$lgz_bin" ]; then
        echo "    [LGZ] ERROR: lgz host binary not found, skipping compression"
        return 1
    fi

    echo "    [LGZ] Using compressor: $lgz_bin"

    # Install the on-device decompressor FIRST: init needs it at
    # /system/bin/lgz for cluster unpack, and the "lgz" basename is in
    # LGZ_EXCLUDE_LIST so the pack scan skips it.
    local target_lgz_dir="$ramdisk_root/system/bin"
    mkdir -p "$target_lgz_dir"
    cp -f "$SCRIPT_DIR/include/lgz_compress_lean_arm64" "$target_lgz_dir/lgz"
    chmod 755 "$target_lgz_dir/lgz"
    echo "    [LGZ] Installed device decompressor to /system/bin/lgz"

    local level="${LGZ_LEVEL:-0}"
    local cluster="$ramdisk_root/lgz_cluster.lgz"
    local pack_manifest packed_list
    pack_manifest=$(mktemp)
    packed_list=$(mktemp)

    echo "# LGZ cluster pack manifest (UCOMP02, generated $(date -u))" > "$pack_manifest"

    # all: every non-excluded file joins (legacy experimental layout).
    # dirs: only files under LGZ_PACK_DIRS join (manual experiment layout).
    local dirs_mode=0
    if [ "$LGZ_POLICY" = "dirs" ]; then
        dirs_mode=1
        echo "    [LGZ] Policy dirs: packing ${#LGZ_PACK_DIRS[@]} listed dirs (excludes win)"
    else
        echo "    [LGZ] Policy all: packing every non-excluded file"
    fi

    # Walk roots: whole ramdisk, or only the listed dirs in dirs mode.
    local scan_roots=()
    if [ "$dirs_mode" -eq 1 ]; then
        local _d
        for _d in "${LGZ_PACK_DIRS[@]}"; do
            _d="${_d#/}"; _d="${_d%/}"  # tolerate leading/trailing slashes
            [ -z "$_d" ] && continue
            if [ -d "$ramdisk_root/$_d" ]; then
                scan_roots+=("$ramdisk_root/$_d")
            else
                echo "    [LGZ] dirs: not in ramdisk, skipped: $_d"
            fi
        done
        if [ "${#scan_roots[@]}" -eq 0 ]; then
            echo "    [LGZ] dirs: no valid dirs — keeping originals"
            rm -f "$pack_manifest" "$packed_list"
            return 0
        fi
    else
        scan_roots=("$ramdisk_root")
    fi

    # Normalize roots: drop exact duplicates and roots nested under another
    # listed root (e.g. PACK_DIRS=("twres/fonts" "twres") would scan the
    # fonts twice and the pack tool fails on the duplicate manifest path).
    if [ "$dirs_mode" -eq 1 ] && [ "${#scan_roots[@]}" -gt 0 ]; then
        local _clean=() _r _s _skip
        for _r in "${scan_roots[@]}"; do
            _skip=0
            for _s in "${scan_roots[@]}"; do
                if [ "$_r" != "$_s" ] && [[ "$_r/" == "$_s/"* ]]; then
                    echo "    [LGZ] dirs: covered by parent root, skipped: ${_r#$ramdisk_root/}"
                    _skip=1
                    break
                fi
            done
            if [ "$_skip" -eq 0 ]; then
                for _s in "${_clean[@]}"; do
                    if [ "$_r" = "$_s" ]; then _skip=1; break; fi
                done
                [ "$_skip" -eq 1 ] && echo "    [LGZ] dirs: duplicate root skipped: ${_r#$ramdisk_root/}"
            fi
            [ "$_skip" -eq 0 ] && _clean+=("$_r")
        done
        scan_roots=("${_clean[@]}")
        if [ "${#scan_roots[@]}" -eq 0 ]; then
            echo "    [LGZ] dirs: no valid dirs after dedup — keeping originals"
            rm -f "$pack_manifest" "$packed_list"
            return 0
        fi
    fi

    # Walk the roots: every regular file joins the
    # cluster unless excluded. *.zip goes through transparent ingestion
    # (DFE.zip gets its NEO.config patched BEFORE packing).
    echo "    [LGZ] Scanning ramdisk tree..."
    declare -A LGZ_SEEN=()
    while IFS= read -r filepath; do
        local relpath="${filepath#$ramdisk_root/}"

        # Skip excluded files (init closure, tooling, generated lists)
        if lgz_is_excluded "$filepath" "$relpath"; then
            continue
        fi

        # Belt and suspenders: never emit one relpath twice (overlapping
        # roots, symlink loops) — the pack tool hard-fails on duplicates.
        if [[ -n "${LGZ_SEEN[$relpath]+x}" ]]; then
            echo "    [LGZ] WARNING: duplicate path skipped: $relpath"
            continue
        fi
        LGZ_SEEN["$relpath"]=1

        case "$filepath" in
            *.zip)
                lgz_patch_dfe_zip "$filepath"
                local zip_size
                zip_size=$(stat -c%s "$filepath" 2>/dev/null || echo 0)
                echo "    [LGZ-ZIP] Ingest: $relpath ($zip_size bytes)"
                lgz_manifest_entry zip "$filepath" "$relpath" >> "$pack_manifest"
                ;;
            *)
                lgz_manifest_entry file "$filepath" "$relpath" >> "$pack_manifest"
                ;;
        esac
        echo "$filepath" >> "$packed_list"
    done < <(for _root in "${scan_roots[@]}"; do find "$_root" -type f; done | sort)

    local entry_count
    entry_count=$(grep -c -E '^(file|zip) ' "$pack_manifest" 2>/dev/null || echo 0)
    # grep -c prints "0" AND fails when nothing matches, so normalize.
    entry_count=$(printf '%s' "$entry_count" | tr -d -c '0-9' | tail -c 20)
    entry_count="${entry_count:-0}"
    if [ "$entry_count" -eq 0 ]; then
        echo "    [LGZ] No files to pack — continuing to snapshot generation"
        rm -f "$pack_manifest" "$packed_list" "$cluster"
        pack_ok=0
    else

    local total_original=0
    while IFS= read -r packed; do
        local sz
        sz=$(stat -c%s "$packed" 2>/dev/null || echo 0)
        total_original=$((total_original + sz))
    done < "$packed_list"

    # Pack: manifest paths are relative, so run from the ramdisk root.
    # --preserve-all stores perms/owner from the FS for correct restore.
    local lgz_jobs
    lgz_jobs=$(lgz_detect_jobs)
    echo "    [LGZ] Packing $entry_count entries (level $level, $lgz_jobs threads)..."
    ( cd "$ramdisk_root" && "$lgz_bin" pack "$pack_manifest" "$cluster" \
        -l "$level" -j "$lgz_jobs" --preserve-all )
    local pack_rc=$?

    local cluster_size
    cluster_size=$(stat -c%s "$cluster" 2>/dev/null || echo 0)

    local pack_ok=1
    if [ "$pack_rc" -ne 0 ]; then
        echo "    [LGZ] ERROR: pack tool failed (rc=$pack_rc, entries=$entry_count) — keeping originals"
        echo "    [LGZ] ERROR: command was: $lgz_bin pack <manifest:$entry_count entries> $cluster -l $level"
        pack_ok=0
    elif [ "$cluster_size" -le 0 ]; then
        echo "    [LGZ] ERROR: pack produced empty cluster — keeping originals"
        pack_ok=0
    elif [ "$cluster_size" -ge "$total_original" ]; then
        echo "    [LGZ] Pack provided no gain (orig $total_original, cluster $cluster_size) — keeping originals"
        pack_ok=0
    elif ! "$lgz_bin" list "$cluster" >/dev/null 2>&1; then
        echo "    [LGZ] ERROR: cluster failed self-check (list) — keeping originals"
        pack_ok=0
    fi

    if [ "$pack_ok" -eq 0 ]; then
        rm -f "$pack_manifest" "$packed_list" "$cluster"
    else
        # Prune originals: the cluster is the only copy now.
        # Only packed files/zips are removed; dirs and symlinks stay in place.
        while IFS= read -r orig; do
            rm -f "$orig"
        done < "$packed_list"
        rm -f "$pack_manifest" "$packed_list"

        local saved=$((total_original - cluster_size))
        local ratio=$((cluster_size * 100 / total_original))
        echo ""
        echo "    [LGZ] ========================================="
        echo "    [LGZ] Cluster pack complete!"
        echo "    [LGZ]   Entries packed:  $entry_count"
        echo "    [LGZ]   Original total:  $total_original bytes"
        echo "    [LGZ]   Cluster total:   $cluster_size bytes"
        echo "    [LGZ]   Space saved:     $saved bytes (${ratio}%)"
        echo "    [LGZ]   Cluster:         /lgz_cluster.lgz"
        echo "    [LGZ] ========================================="
    fi
    fi # entry_count > 0 (pack attempted)

    # NOTE: snapshot/file-list generation below ALWAYS runs, even when
    # packing was skipped or failed — reflash needs these lists.

    # Generate ramdisk snapshot manifest and cpio file lists using find.
    # We build our own manifest instead of relying on builder-generated
    # ramdisk-files.txt (which may not exist when this callback runs).
    local snapshot_manifest="$ramdisk_root/ramdisk_snapshot_manifest.txt"

    # Derive vendor_ramdisk path (first_stage ramdisk is a separate directory)
    # recovery/root/ -> product_out/vendor_ramdisk/
    local product_out
    product_out="$(dirname "$(dirname "$ramdisk_root")")"
    local vendor_ramdisk_dir="$product_out/vendor_ramdisk"

    echo "    [LGZ] Generating ramdisk snapshot manifest..."

    # Create file lists FIRST so they are discovered by the manifest find.
    # This ensures ramdisk_snapshot copies them to the snapshot at runtime.

    # 1. Recovery cpio file list (everything in recovery/root/)
    pushd "$ramdisk_root" > /dev/null
    find . | sed 's|^\./||; /^$/d' | sort > "$ramdisk_root/recovery_file_list.txt"
    popd > /dev/null

    # 2. First stage ramdisk cpio file list (from vendor_ramdisk/ directory)
    if [ -d "$vendor_ramdisk_dir/first_stage_ramdisk" ]; then
        pushd "$vendor_ramdisk_dir" > /dev/null
        find first_stage_ramdisk | sort > "$ramdisk_root/first_stage_file_list.txt"
        popd > /dev/null
        echo "    [LGZ] First stage ramdisk found at: $vendor_ramdisk_dir"
    else
        echo "    [LGZ] WARNING: vendor_ramdisk/first_stage_ramdisk not found"
    fi

    # 3. Comprehensive manifest with permissions for ramdisk_snapshot binary
    # Generated AFTER file lists so they are included in the manifest.
    {
        echo "# Ramdisk snapshot manifest"
        echo "# Format: <type> <octal_perms> <uid> <gid> <path>"
        echo "# For symlinks: l <perms> <uid> <gid> <path> -> <target>"
        echo "# Generated: $(date -u)"

        # Recovery ramdisk entries
        pushd "$ramdisk_root" > /dev/null
        find . \( -type l -printf 'l %m %U %G %p -> %l\n' \) \
               -o \( -type d -printf 'd %m %U %G %p\n' \) \
               -o \( -type f -printf 'f %m %U %G %p\n' \) | \
            sed 's| \.$| /|; s| \./| /|'
        popd > /dev/null

        # Vendor ramdisk (first_stage) entries
        if [ -d "$vendor_ramdisk_dir" ]; then
            pushd "$vendor_ramdisk_dir" > /dev/null
            find . -mindepth 1 \( -type l -printf 'l %m %U %G %p -> %l\n' \) \
                   -o \( -type d -printf 'd %m %U %G %p\n' \) \
                   -o \( -type f -printf 'f %m %U %G %p\n' \) | \
                sed 's| \./| /|'
            popd > /dev/null
        fi
    } | sort -t' ' -k5 > "$snapshot_manifest"

    local snap_count recovery_count fstage_count
    snap_count=$(grep -c '^[dfl]' "$snapshot_manifest" 2>/dev/null || echo 0)
    recovery_count=$(wc -l < "$ramdisk_root/recovery_file_list.txt" 2>/dev/null || echo 0)
    fstage_count=$(wc -l < "$ramdisk_root/first_stage_file_list.txt" 2>/dev/null || echo 0)
    echo "    [LGZ] Ramdisk snapshot manifest: $snap_count entries"
    echo "    [LGZ] Recovery cpio file list: $recovery_count entries"
    echo "    [LGZ] First stage cpio file list: $fstage_count entries"
}

# =========================================================================
# Main callback logic
# =========================================================================

case "$CALL_TYPE" in
    --first-call)
        echo "=== [zuma] fox_build_callback: --first-call ==="
        echo "    Ramdisk: $TARGET_DIR"
        # NOTE: UI XML pages are patched natively in the tree
        # (patches/files/.../pages/*.xml) — no overlay step needed.
        ;;

    --second-call)
        echo "=== [zuma] fox_build_callback: --second-call ==="
        echo "    Ramdisk: $TARGET_DIR (final, pre-cpio)"

        # --- Per-family twrp.flags injection ---
        # Every family ships its own families/<fam>/twrp.flags (UFS paths
        # differ per SoC); the ramdisk default is replaced unconditionally.
        platform="$PLATFORM"
        fam_flags="$SCRIPT_DIR/families/$platform/twrp.flags"
        default_flags="$TARGET_DIR/system/etc/twrp.flags"
        if [ -f "$fam_flags" ]; then
            echo "    [PLATFORM] Injecting twrp.flags for $platform"
            cp -f "$fam_flags" "$default_flags"
        else
            echo "    [PLATFORM] ERROR: family flags missing: $fam_flags"
        fi

        # --- Per-device twrp.flags overrides ---
        # A device may ship devices/<codename>/twrp.flags; the builder
        # stores it as /system/etc/<device>.twrp.flags and the Rust init
        # swaps it over the default once ro.hardware is known.
        for dev_flags in "$SCRIPT_DIR"/devices/*/twrp.flags; do
            [ -f "$dev_flags" ] || continue
            dev=$(basename "$(dirname "$dev_flags")")
            cp -f "$dev_flags" "$TARGET_DIR/system/etc/${dev}.twrp.flags"
            echo "    [PLATFORM]   + device override: ${dev}.twrp.flags"
        done

        # --- Per-platform keymint binary injection ---
        # Zuma/Zumapro use the shared prebuilt Rust keymint from
        # families/common/keymint/bin/hw/ (one binary for both).
        # GS201 uses C++ keymint built from source (system/core/trusty/keymaster)
        # via PRODUCT_PACKAGES; soong places it at $PRODUCT_OUT/vendor/bin/hw/.
        # VINTF keymint fragments live in families/<platform>/etc/.
        family_dir="$SCRIPT_DIR/families/$platform"
        common_keymint_bin="$SCRIPT_DIR/families/common/keymint/bin"
        PRODUCT_OUT="${TARGET_DIR%/recovery/root}"

        echo "    [PLATFORM] Injecting keymint for: $platform"

        # --- Keymint binary ---
        # C++ from source: gs201 always; zuma only under TEST toggle
        # (FOX_ZUMA_CPP_KEYMINT=1). Else Rust prebuilt (zuma/zumapro).
        use_cpp_keymint=0
        if [ "$platform" = "gs201" ]; then
            use_cpp_keymint=1
        elif [ "$platform" = "zuma" ] && [ "$ZUMA_CPP_KEYMINT" = "1" ]; then
            use_cpp_keymint=1
        fi
        if [ "$use_cpp_keymint" = "1" ]; then
            # GS201 / zuma-TEST: copy source-built C++ keymint from soong vendor output
            src_bin="$PRODUCT_OUT/vendor/bin/hw/android.hardware.security.keymint-service.trusty"
            if [ -f "$src_bin" ]; then
                mkdir -p "$TARGET_DIR/vendor/bin/hw"
                cp -f "$src_bin" "$TARGET_DIR/vendor/bin/hw/"
                chmod 755 "$TARGET_DIR/vendor/bin/hw/android.hardware.security.keymint-service.trusty"
                echo "    [PLATFORM]   + C++ keymint binary (source-built)"
            else
                echo "    [PLATFORM] ERROR: C++ keymint binary not found at: $src_bin"
                echo "    [PLATFORM]   Ensure PRODUCT_PACKAGES includes keymint-service.trusty"
            fi
        else
            # Zuma/Zumapro: copy shared prebuilt Rust keymint
            if [ -d "$common_keymint_bin" ]; then
                cp -af "$common_keymint_bin" "$TARGET_DIR/vendor/"
                find "$TARGET_DIR/vendor/bin/hw" -type f -exec chmod 755 {} +
                echo "    [PLATFORM]   + Rust keymint binary (prebuilt)"
            else
                echo "    [PLATFORM] WARNING: No prebuilt keymint bin dir"
            fi
        fi

        # --- VINTF keymint fragment (per family) ---
        if [ -d "$family_dir/etc" ]; then
            cp -af "$family_dir/etc" "$TARGET_DIR/vendor/"
            echo "    [PLATFORM]   + VINTF keymint fragment"
        fi

        # --- Disable the keymint service that doesn't match this platform ---
        rc_file="$TARGET_DIR/init.recovery.pixel_common.rc"
        if [ -f "$rc_file" ]; then
            if [ "$use_cpp_keymint" = "1" ]; then
                # GS201 / zuma-TEST: disable Rust keymint start (no Rust binary)
                sed -i 's/^\(    start vendor\.keymint\.rust-trusty\)/#\1  # disabled for '"$platform"'/' "$rc_file"
                echo "    [PLATFORM]   + disabled Rust keymint start"
            else
                # Zuma/Zumapro: disable C++ keymint start (no C++ binary)
                sed -i 's/^\(    start vendor\.keymint-trusty\)/#\1  # disabled for '"$platform"'/' "$rc_file"
                echo "    [PLATFORM]   + disabled C++ keymint start"
            fi
        fi

        # --- Pixel device config: merge per-device JSON for the Rust engine ---
        echo "    [PIXELCFG] Merging device configs..."
        merge_pixel_config "$TARGET_DIR" "$PLATFORM" || return 1

        # --- INIT-STUB: real init rides the cluster, stub takes its place ---
        # Must run BEFORE lgz_compress_ramdisk + manifest generation below:
        # "init" is in LGZ_EXCLUDE_LIST (stays open), "init.real" is not
        # (packs via system/bin), and the file lists must reference final
        # names. If the swap is skipped the build still boots via the
        # init.cpp unpack fallback — warn loudly, do not fail.
        if [ -x "$TARGET_DIR/system/bin/init" ] && [ -f "$TARGET_DIR/system/bin/recovery_init_stub" ]; then
            mv -f "$TARGET_DIR/system/bin/init" "$TARGET_DIR/system/bin/init.real"
            mv -f "$TARGET_DIR/system/bin/recovery_init_stub" "$TARGET_DIR/system/bin/init"
            chmod 0755 "$TARGET_DIR/system/bin/init"
            echo "    [INIT-STUB] real init -> init.real, stub installed as init"
        else
            echo "    [INIT-STUB] WARNING: init or recovery_init_stub missing, swap skipped (init.cpp fallback)"
        fi

        # --- LGZ: Compress ramdisk binaries for space savings ---
        echo ""
        echo "    === LGZ Ramdisk Compression ==="
        lgz_compress_ramdisk "$TARGET_DIR"
        echo ""
        ;;

    --last-call)
        echo "=== [zuma] fox_build_callback: --last-call ==="
        echo "    Working dir: $TARGET_DIR"
        # No additional actions needed for the zip phase
        ;;

    *)
        echo "Unknown call type: $CALL_TYPE"
        ;;
esac

exit 0
