# families/zuma/family.mk — Tensor G3 (also the fallback family).
# Included by BoardConfig.mk when DEVICE_BUILD_FLAG=zuma (or empty).

# VENDOR_CMDLINE default (6.1-era). Kernel-specific command lines live in
# family.json `kernels` and arrive via .gen_kernel.mk (generated by
# gen_kernel_mk.py from build.sh -k); the generated file is included at the
# end of BoardConfig.mk and overrides this default when present.
VENDOR_CMDLINE := "dyndbg=\"func alloc_contig_dump_pages +p\" \
        earlycon=exynos4210,0x10A00000 \
        console=ttySAC0,115200 \
        androidboot.console=ttySAC0 \
        printk.devkmsg=on \
        swiotlb=noforce \
        cma_sysfs.experimental=Y \
        cgroup_disable=memory \
        rcupdate.rcu_expedited=1 \
        androidboot.usbcontroller=11210000.dwc3 \
        rcu_nocbs=all \
        stack_depot_disable=off \
        page_pinner=on \
        swiotlb=1024 \
        disable_dma32=on \
        at24.write_timeout=100 \
        log_buf_len=1024K \
        bootconfig"
BOARD_BOOTCONFIG += androidboot.boot_devices=13200000.ufs
BOARD_BOOTCONFIG += androidboot.load_modules_parallel=true
# NOTE: androidboot.usbcontroller is kernel-version-specific and arrives via
# .gen_kernel.mk (bootconfig_append) when build.sh -k is used. No default
# here — keeps the 6.12 profile (empty append) from inheriting it.

# Partitions - Blocks
BOARD_FLASH_BLOCK_SIZE := 131072
