# families/zumapro/family.mk — Tensor G4.
# Included by BoardConfig.mk when DEVICE_BUILD_FLAG=zumapro.
#
# Kernel cmdline + bootconfig live in family.json `kernels` and arrive via
# families/zumapro/.gen_kernel.mk (generated by gen_kernel_mk.py from
# build.sh -k). No hardcoded VENDOR_CMDLINE/BOARD_BOOTCONFIG here by design.

# Partitions - Blocks
BOARD_FLASH_BLOCK_SIZE := 4096
