# families/gs101/family.mk — Tensor G1 (Pixel 6 series).
#
# Kernel cmdline + bootconfig live in family.json `kernels` and arrive via
# families/gs101/.gen_kernel.mk (generated by gen_kernel_mk.py from
# build.sh -k). No hardcoded VENDOR_CMDLINE/BOARD_BOOTCONFIG here by design.
#
# gs101 vendor_boot layout (NO vendor_kernel_boot partition on Tensor G1):
# stock carries platform + dlkm + dtb fragments. Our build produces a SINGLE
# platform fragment (first-stage + recovery merged via
# BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT with
# BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT=false, see BoardConfig.mk),
# no dtb, no dlkm fragment. Stock kernel modules ride INSIDE our platform
# (families/gs101/modules/, copied below) so first-stage init brings up UFS
# exactly like stock. Post-processing (build.sh gs101 block) extracts the
# platform ramdisk as lz4_legacy for `fastboot flash vendor_boot:default`.

# Partitions - Blocks
BOARD_FLASH_BLOCK_SIZE := 131072

# First-stage kernel modules (stock LOS 6.1.145, cannot be built from source):
# 204 .ko + modules.{load,dep,alias,softdep,blocklist} land at /lib/modules/
# in the platform ramdisk, same path as the stock dlkm fragment overlay.
GS101_MODULES_DIR := $(DEVICE_PATH)/families/gs101/modules/lib/modules
PRODUCT_COPY_FILES += $(foreach f,$(wildcard $(GS101_MODULES_DIR)/*.ko),$(f):$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/modules/$(notdir $(f)))
PRODUCT_COPY_FILES += $(GS101_MODULES_DIR)/modules.load:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/modules/modules.load
PRODUCT_COPY_FILES += $(GS101_MODULES_DIR)/modules.dep:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/modules/modules.dep
PRODUCT_COPY_FILES += $(GS101_MODULES_DIR)/modules.alias:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/modules/modules.alias
PRODUCT_COPY_FILES += $(GS101_MODULES_DIR)/modules.softdep:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/modules/modules.softdep
PRODUCT_COPY_FILES += $(GS101_MODULES_DIR)/modules.blocklist:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/modules/modules.blocklist
