# families/gs101/family.mk — Tensor G1 (Pixel 6 series).
#
# Kernel cmdline + bootconfig live in family.json `kernels` and arrive via
# families/gs101/.gen_kernel.mk (generated by gen_kernel_mk.py from
# build.sh -k). No hardcoded VENDOR_CMDLINE/BOARD_BOOTCONFIG here by design.
#
# gs101 vendor_boot layout (NO vendor_kernel_boot partition on Tensor G1):
# stock carries platform + dlkm + dtb fragments. Our build produces a SINGLE
# platform fragment (first-stage + recovery merged via
# BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT with
# BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT=false, see BoardConfig.mk),
# no dtb, no dlkm fragment, no kernel modules inside. Flashing is fragment
# surgery: `fastboot flash vendor_boot: <ramdisk>` (empty name = the
# platform fragment; NOT :default, which would collapse the whole section
# into one entry and kill dlkm) replaces ONLY that entry — stock dlkm+dtb
# survive, first-stage keeps autoloading all stock modules from dlkm.
# Everything past that (touch/drm/keymint) the engine loads from the
# vendor_dlkm partition at runtime, like on all other families.
# Post-processing (build.sh gs101 block) extracts the platform ramdisk as
# lz4_legacy for that command.

# Partitions - Blocks
BOARD_FLASH_BLOCK_SIZE := 131072
