# families/gs101/family.mk — Tensor G1 (WIP, reuses gs201 fstab).
# Included by BoardConfig.mk when DEVICE_BUILD_FLAG=gs101.
#
# Kernel cmdline + bootconfig live in family.json `kernels` and arrive via
# families/gs101/.gen_kernel.mk (generated by gen_kernel_mk.py from
# build.sh -k). No hardcoded VENDOR_CMDLINE/BOARD_BOOTCONFIG here by design.
# (Historical note: this file once carried a double VENDOR_CMDLINE
# assignment — the second one won — and a BOARD_BOOTCONFIG `:=` reset to
# usbcontroller=11110000.dwc3. Both quirks are preserved verbatim in the
# family.json 6.1 profile above.)

# Partitions - Blocks
BOARD_FLASH_BLOCK_SIZE := 131072

# gs101: vendor_boot contains DLKM+DTB — must patch stock, not overwrite
VENDOR_BOOT_PATCH_STOCK := true
-include $(DEVICE_PATH)/custom_bootimg.mk
