# families/malibu/family.mk — Tensor G6 (Pixel 11 Pro / grizzly).
# Included by BoardConfig.mk when DEVICE_BUILD_FLAG=malibu.
#
# Kernel cmdline + bootconfig live in family.json `kernels` and arrive via
# families/malibu/.gen_kernel.mk (generated by gen_kernel_mk.py from
# build.sh -k). No hardcoded VENDOR_CMDLINE/BOARD_BOOTCONFIG here by design.

# Partitions - Blocks
BOARD_FLASH_BLOCK_SIZE := 131072
